# -*- coding: utf-8 -*-
"""EDA Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AnIiizmsApAEySp850n48SUtZzvcRuz
"""

"""
Universal Dataset Analysis - EDA Report Generator
Run this after installing: pip install setuptools ydata-profiling pandas numpy
Usage: python iris_analysis.py [path_to_data_file.csv]
"""

import os
import sys
import argparse

print("=" * 60)
print("    UNIVERSAL DATASET ANALYSIS - EDA REPORT GENERATOR")
print("=" * 60)
print()

# ===================================
# Step 1: Import libraries
# ===================================
print("Step 1: Importing libraries...")
print("-" * 60)

try:
    import pandas as pd
    import numpy as np
    from ydata_profiling import ProfileReport
    print("✓ All libraries imported successfully!")
    print()
except ImportError as e:
    print(f"❌ Error: {e}")
    print()
    print("Please install the required packages:")
    print("  pip install setuptools ydata-profiling pandas numpy")
    print()
    input("Press Enter to exit...")
    sys.exit(1)

# ===================================
# Step 2: Get data file path
# ===================================
print("📂 Step 2: Getting data file path...")
print("-" * 60)
current_dir = os.getcwd()
print(f"  Current directory: {current_dir}")
print()

# Check for command line argument
if len(sys.argv) > 1:
    data_file = sys.argv[1]
    print(f"  Using file from command line: {data_file}")
else:
    # Prompt user for file path
    print("  Please enter the path to your data file (CSV format):")
    print("  (You can drag and drop the file here, or type the path)")
    data_file = input("  File path: ").strip().strip('"').strip("'")
    print()

# Validate file exists
if not os.path.exists(data_file):
    print(f"❌ Error: File not found: {data_file}")
    print()
    input("Press Enter to exit...")
    sys.exit(1)

# Get base filename for output
base_name = os.path.splitext(os.path.basename(data_file))[0]
print(f"  ✓ File found: {data_file}")
print(f"  ✓ Output report will be named: {base_name}_eda_report.html")
print()

# ===================================
# Step 3: Load dataset
# ===================================
print("📊 Step 3: Loading dataset...")
print("-" * 60)

try:
    # Try to detect delimiter and encoding
    print("  Reading CSV file...")

    # Try common encodings
    encodings = ['utf-8', 'latin-1', 'cp1252', 'iso-8859-1']
    df = None

    for encoding in encodings:
        try:
            # Try to read with different delimiters
            for delimiter in [',', ';', '\t', '|']:
                try:
                    df = pd.read_csv(data_file, encoding=encoding, delimiter=delimiter, low_memory=False)
                    if len(df.columns) > 1:  # Valid CSV should have multiple columns
                        print(f"  ✓ Detected delimiter: '{delimiter}', encoding: {encoding}")
                        break
                except:
                    continue
            if df is not None:
                break
        except:
            continue

    # If still None, try default pandas read_csv
    if df is None:
        df = pd.read_csv(data_file, low_memory=False)
        print("  ✓ Using default CSV settings")

    print(f"✓ Dataset loaded successfully!")
    print(f"  • Total rows: {len(df)}")
    print(f"  • Total columns: {len(df.columns)}")
    print(f"  • Columns: {', '.join(df.columns.tolist()[:10])}")  # Show first 10 columns
    if len(df.columns) > 10:
        print(f"    ... and {len(df.columns) - 10} more columns")
    print()

except Exception as e:
    print(f"❌ Error loading dataset: {e}")
    print()
    print("Common issues:")
    print("  • Make sure the file is a valid CSV format")
    print("  • Check if the file path is correct")
    print("  • Try opening the file in Excel/LibreOffice to verify it's valid")
    print()
    input("Press Enter to exit...")
    sys.exit(1)

# ===================================
# Step 4: Show preview
# ===================================
print("👀 Step 4: Data preview (first 5 rows)...")
print("-" * 60)
print(df.head().to_string())
print()

# ===================================
# Step 5: Show basic info
# ===================================
print("📊 Step 5: Basic statistics...")
print("-" * 60)
print(df.describe().to_string())
print()

print("🔍 Missing values check:")
print("-" * 60)
missing = df.isnull().sum()
print(missing.to_string())
print(f"Total missing values: {missing.sum()}")
print()

print("📋 Data types:")
print("-" * 60)
print(df.dtypes.to_string())
print()

# ===================================
# Step 6: Generate EDA Report
# ===================================
print("🚀 Step 6: Generating comprehensive EDA report...")
print("-" * 60)
print("⏳ This will take 1-2 minutes, please wait...")
print()

try:
    # Create profile report
    profile = ProfileReport(
        df,
        title=f"{base_name} Dataset - Exploratory Data Analysis Report",
        explorative=True,
        minimal=False,
        correlations={
            "pearson": {"calculate": True},
            "spearman": {"calculate": True},
            "kendall": {"calculate": False},
            "phi_k": {"calculate": False},
        },
        interactions={"continuous": True},
        missing_diagrams={
            "bar": True,
            "matrix": True,
            "heatmap": True,
        },
    )

    print("✓ Profile report object created successfully!")
    print()

    # Save report with dynamic name
    output_file = os.path.join(current_dir, f"{base_name}_eda_report.html")

    print(f"💾 Saving report...")
    print(f"   Location: {output_file}")
    print()

    profile.to_file(output_file)

    # Verify file exists
    if os.path.exists(output_file):
        file_size = os.path.getsize(output_file)
        file_size_kb = file_size / 1024
        file_size_mb = file_size_kb / 1024

        print()
        print("=" * 60)
        print("✅ SUCCESS! REPORT GENERATED")
        print("=" * 60)
        print(f"📄 File name: {base_name}_eda_report.html")
        print(f"📍 Location: {current_dir}")
        print(f"📊 File size: {file_size:,} bytes ({file_size_kb:.2f} KB)")
        print("=" * 60)
        print()

        # List all HTML files
        print("📁 HTML files in current directory:")
        print("-" * 60)
        html_files = [f for f in os.listdir(current_dir) if f.endswith('.html')]
        if html_files:
            for f in html_files:
                f_path = os.path.join(current_dir, f)
                f_size = os.path.getsize(f_path)
                print(f"  • {f} ({f_size:,} bytes)")
        else:
            print("  (No HTML files found)")
        print()

        # Try to open in browser
        print("💡 Opening report in your default browser...")
        print("-" * 60)
        try:
            import subprocess
            if sys.platform == 'win32':
                os.startfile(output_file)
                print("✓ Report opened in browser!")
            elif sys.platform == 'darwin':  # macOS
                subprocess.call(['open', output_file])
                print("✓ Report opened in browser!")
            else:  # linux
                subprocess.call(['xdg-open', output_file])
                print("✓ Report opened in browser!")
        except Exception as e:
            print(f"⚠️  Could not auto-open browser: {e}")
            print(f"📌 Please open manually: {output_file}")

        print()
        print("=" * 60)
        print("🎉 ANALYSIS COMPLETE!")
        print("=" * 60)
        print()
        print("The HTML report contains:")
        print("  ✓ Overview of the dataset")
        print("  ✓ Variable statistics and distributions")
        print("  ✓ Correlation matrices")
        print("  ✓ Missing values analysis")
        print("  ✓ Sample data")
        print("  ✓ Interactive charts and graphs")
        print()

    else:
        print()
        print("=" * 60)
        print("❌ ERROR: File was not created!")
        print("=" * 60)
        print(f"Expected location: {output_file}")
        print()

except Exception as e:
    print()
    print("=" * 60)
    print("❌ ERROR DURING REPORT GENERATION")
    print("=" * 60)
    print(f"Error type: {type(e).__name__}")
    print(f"Error message: {str(e)}")
    print()

    import traceback
    print("Full error details:")
    print("-" * 60)
    print(traceback.format_exc())
    print()

    input("Press Enter to exit...")
    sys.exit(1)

# Keep window open
print()
input("Press Enter to exit...")
